In [1]:
import modin.pandas as pd

In [13]:
df=pd.read_csv("C:/Users/Owner/Documents/GITHUB/air_pollution/Final_Dataset_Project3.csv")

In [14]:
df

,State_Code,County_Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,Farm Count
0,54,61.0,5.0,42401.0,1.0,39.648414,-79.957563,WGS84,Sulfur dioxide,3-HR BLK AVG,...,0.0,136.0,90.0,50.0,0.0,0.0,158.0,98.0,2.0,NaN
1,54,69.0,7.0,42401.0,1.0,40.120502,-80.699067,WGS84,Sulfur dioxide,1 HOUR,...,0.0,182.0,101.0,44.0,102.0,0.0,188.0,74.0,1.0,NaN
2,54,69.0,7.0,42401.0,1.0,40.120502,-80.699067,WGS84,Sulfur dioxide,1 HOUR,...,0.0,182.0,101.0,44.0,102.0,0.0,188.0,74.0,1.0,NaN
3,54,69.0,7.0,42401.0,1.0,40.120502,-80.699067,WGS84,Sulfur dioxide,24-HR BLK AVG,...,0.0,182.0,101.0,44.0,102.0,0.0,188.0,74.0,1.0,NaN
4,54,69.0,7.0,42401.0,1.0,40.120502,-80.699067,WGS84,Sulfur dioxide,3-HR BLK AVG,...,0.0,182.0,101.0,44.0,102.0,0.0,188.0,74.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2366771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2366772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36
2366773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116
2366774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,764
2366775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150